@host=localhost:5000

### Login user
POST http://{{host}}/api/auth/login
content-type: application/json

{
    "login": "test",
    "password": "test"
}

?? status == 200

@token={{response.parsedBody.token}}

### Create user
POST http://{{host}}/api/users
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Test3",
    "login": "test3",
    "password": "test"
}

?? status == 201

### Get user
GET http://{{host}}/api/users/2
Authorization: Bearer {{token}}
content-type: application/json

?? status == 200

### Get all users
GET http://{{host}}/api/users
Authorization: Bearer {{token}}
content-type: application/json

?? status == 200

### Change user password
PATCH http://{{host}}/api/users/changepass
Authorization: Bearer {{token}}
content-type: application/json

{
    "id": 4,
    "password": "test",
    "new_password": "test"
}

?? status == 202

### Update user 
PUT http://{{host}}/api/users/
Authorization: Bearer {{token}}
content-type: application/json

{
    "id": 1,
    "name": "Bob Updated",
    "login": "bob_updated",
    "password": "bob_new"
}

?? status == 200

### Delete user 
DELETE http://{{host}}/api/users/1
Authorization: Bearer {{token}}
content-type: application/json

?? status == 200